# Generated by Django 2.2.1 on 2019-06-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Descrição',
                'verbose_name_plural': 'Descrições',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.IntegerField(blank=True, verbose_name='Código Interno')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Diametro')),
                ('cutterLength', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura de Corte')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Descrição', to='tools.TypeItem')),
            ],
            options={
                'verbose_name': 'Nome',
                'verbose_name_plural': 'Nomes',
                'ordering': ['diameter'],
            },
        ),
    ]
