# Generated by Django 2.2.1 on 2019-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_code',
            field=models.IntegerField(verbose_name='Código Interno'),
        ),
    ]
