# Generated by Django 2.2.1 on 2019-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20190602_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_code',
            field=models.IntegerField(blank=True, verbose_name='Código Interno'),
        ),
    ]
