# Generated by Django 2.2.1 on 2019-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20190602_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_code',
            field=models.IntegerField(null=True, verbose_name='Código Interno'),
        ),
    ]
