# Generated by Django 2.2.1 on 2019-06-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20190602_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Interno'),
        ),
    ]
